### ISSUE TITLE
s3 DeleteObjectsRequest delete non-existing-Objects fails

### ISSUE THREAD

**Issue by qeepcologne** [aws/aws-sdk-java-v2#1363]
I'm trying to delete multiple keys from s3 and it fails.

## Expected Behavior
With sdk 2.6.5 everything work fine. The existing keys are deleted and the non-existing keys are ignored.

## Current Behavior
With sdk 2.7.11 deletion fails if some keys doesn't exist.

I am using the DeleteObjectsRequest to delete all variants of an image. Image variants (different sizes, blurred versions etc.) are created via not found redirect to api gateway, create via lambda and redirect back. So i don't know which variants exist in my backend and just try to delete all.

## Steps to Reproduce (for bugs)
    private void deleteInternal(final List<String> keysToDel) {
        List<ObjectIdentifier> objToDel = keysToDel.stream().map(key -> ObjectIdentifier.builder().key(key).build()).collect(Collectors.toList());

        try {
            client.deleteObjects(DeleteObjectsRequest.builder().bucket(bucketName).delete(Delete.builder().objects(objToDel).build()).build());
        } catch (SdkException ex) {
            logDebugDetails(ex);
            throw new RuntimeException("Failed to delete object from amazon s3: " + bucketName + "," + Arrays.toString(keysToDel.toArray()) + "," + ex.getMessage(), ex);
        }
    }

and receive:

java.lang.RuntimeException: Failed to delete object from amazon s3: qeep-images-test,[0856/360856/110355722-1080.jpeg, 0856/360856/110355722-1080_blur.jpeg, 0856/360856/110355722-1080_720.jpeg, 0856/360856/110355722-1080_blur_720.jpeg, 0856/360856/110355722-1080_512.jpeg, 0856/360856/110355722-1080_blur_512.jpeg, 0856/360856/110355722-1080_360.jpeg, 0856/360856/110355722-1080_blur_360.jpeg, 0856/360856/110355722-1080_256.jpeg, 0856/360856/110355722-1080_blur_256.jpeg, 0856/360856/110355722-1080_180.jpeg, 0856/360856/110355722-1080_blur_180.jpeg, 0856/360856/110355722-1080_128.jpeg, 0856/360856/110355722-1080_blur_128.jpeg],null (Service: S3, Status Code: 302, Request ID: null)

I think this is not the documented behaviour, if you are interested getting the failures, set quiet mode and check the result.

## Your Environment

* AWS Java SDK version used: 2.6.5 (ok), 2.7.10, 2.7.11 (broken)
* JDK version used: 12.02
* Operating System and version: Oracle Linux Server 7.6

**Comment by zoewangg** [comment]
Thank you for reporting. This issue is caused by a regression introduced in the apache client `4.5.9` that SDK `2.7.x` recently upgraded to.

We will work on the fix.

**Comment by bmaizels** [comment]
Hello, could you confirm which version of Apache HttpClient you are using in your dependency tree?

We are able to repro a similar bug to the one you reported when using a combination of the AWS SDK 2.7.x and Apache HttpClient 4.5.8, but not for the version of Apache HttpClient the SDK pins as default which is 4.5.9. This is due to a behavioral change that was introduced in 4.5.8 which effectively broke parts of the AWS SDK but was then remedied in 4.5.9 (by means of a software toggle that we could use to enforce the old behavior). Unfortunately this means that the AWS SDK 2.7.x will never work properly with the specific Apache HttpClient version 4.5.8 as that switch is not available to us in that version.

If you think this may be the issue you are having, our recommendation would be to upgrade your Apache HttpClient version to 4.5.9 to be in line with the pinned version we released the 2.7.x SDK with.

Please let us know if this fixes the behavior you have observed.

**Comment by qeepcologne** [comment]
Thanks for the helpful answer. You are right, we were using HttpClient 4.5.8 and updating to 4.5.9 solved the problem with aws sdk 2.7.x.
