### ISSUE TITLE
SQS: Interrupt long polling

### ISSUE THREAD

**Issue by tmartins1** [aws/aws-sdk-java-v2#1395]
After canceling the CompletableFuture returned by the receive call, SQS shouldn't send messages through that connection. After testing I think that's what's happening. I also found this [comment](https://github.com/aws/aws-sdk-js/issues/2350#issuecomment-438463015) that talks about the same thing.

## Expected Behavior

To close a receive message call with SqsAsyncClient, it is just needed to cancel the CompletableFuture and SQS shouldn't use that connection to send messages that are in the queue.

## Current Behavior

What's I think is happening is the connection is "alive" in the SQS side and it sends a message through it. As it is closed, then the message doesn't get received and it has to wait for the visibility timeout to be available to other subscribers.

## Steps to Reproduce (for bugs)

In this example, just the first message is received and after checking the queue attributes, I noticed that "ApproximateNumberOfMessagesNotVisible" is 1.  

    import com.google.common.collect.ImmutableMap;
    import software.amazon.awssdk.services.sns.SnsClient;
    import software.amazon.awssdk.services.sns.model.CreateTopicRequest;
    import software.amazon.awssdk.services.sns.model.CreateTopicResponse;
    import software.amazon.awssdk.services.sns.model.PublishRequest;
    import software.amazon.awssdk.services.sns.model.SubscribeRequest;
    import software.amazon.awssdk.services.sqs.SqsAsyncClient;
    import software.amazon.awssdk.services.sqs.SqsClient;
    import software.amazon.awssdk.services.sqs.model.CreateQueueRequest;
    import software.amazon.awssdk.services.sqs.model.CreateQueueResponse;
    import software.amazon.awssdk.services.sqs.model.DeleteMessageRequest;
    import software.amazon.awssdk.services.sqs.model.GetQueueAttributesRequest;
    import software.amazon.awssdk.services.sqs.model.GetQueueAttributesResponse;
    import software.amazon.awssdk.services.sqs.model.QueueAttributeName;
    import software.amazon.awssdk.services.sqs.model.ReceiveMessageRequest;
    import software.amazon.awssdk.services.sqs.model.ReceiveMessageResponse;
    import software.amazon.awssdk.services.sqs.model.SetQueueAttributesRequest;

    import java.net.URISyntaxException;
    import java.util.Map;
    import java.util.concurrent.CompletableFuture;
    import java.util.concurrent.ExecutionException;
    import java.util.concurrent.TimeUnit;
    import java.util.concurrent.TimeoutException;

    public class Main {
        public static void main(String[] args) throws ExecutionException, InterruptedException, TimeoutException, URISyntaxException {
            SnsClient snsClient;
            SqsClient sqsClient;
            SqsAsyncClient sqsAsyncClient;

            snsClient = SnsClient.create();
            sqsClient = SqsClient.create();
            sqsAsyncClient = SqsAsyncClient.create();

            CreateTopicResponse topic = snsClient.createTopic(CreateTopicRequest.builder().name("test").build());
            CreateQueueResponse queue = sqsClient.createQueue(CreateQueueRequest.builder().queueName("test").build());

            GetQueueAttributesRequest getQueueAttributesRequest = GetQueueAttributesRequest.builder()
                    .queueUrl(queue.queueUrl())
                    .attributeNames(QueueAttributeName.QUEUE_ARN)
                    .build();
            GetQueueAttributesResponse getQueueAttributesResult = sqsClient.getQueueAttributes(getQueueAttributesRequest);
            String queueArn = getQueueAttributesResult.attributes().get(QueueAttributeName.QUEUE_ARN);

            Map<QueueAttributeName, String> policy = ImmutableMap.of(QueueAttributeName.POLICY, String.format("{\n" +
                    "  \"Version\": \"2012-10-17\",\n" +
                    "  \"Id\": \"SQSSendMessagePolicy\",\n" +
                    "  \"Statement\": [\n" +
                    "    {\n" +
                    "      \"Sid\": \"SQSSendMessage\",\n" +
                    "      \"Effect\": \"Allow\",\n" +
                    "      \"Principal\": \"*\",\n" +
                    "      \"Action\": [\n" +
                    "        \"SQS:SendMessage\"\n" +
                    "      ],\n" +
                    "      \"Resource\": [\n" +
                    "        \"%s\"\n" +
                    "      ]\n" +
                    "    }\n" +
                    "  ]\n" +
                    "}", queueArn));

            sqsClient.setQueueAttributes(SetQueueAttributesRequest.builder().queueUrl(queue.queueUrl()).attributes(policy).build());

            SubscribeRequest subscribeRequest = SubscribeRequest.builder()
                    .topicArn(topic.topicArn())
                    .protocol("sqs")
                    .endpoint(queueArn)
                    .build();

            snsClient.subscribe(subscribeRequest);

            ReceiveMessageRequest request = ReceiveMessageRequest.builder()
                    .queueUrl(queue.queueUrl())
                    .visibilityTimeout(20)
                    .waitTimeSeconds(20)
                    .maxNumberOfMessages(1)
                    .build();

            CompletableFuture<ReceiveMessageResponse> futureResponse1 = sqsAsyncClient.receiveMessage(request);
            snsClient.publish(PublishRequest.builder().topicArn(topic.topicArn()).message("hello1").build());
            ReceiveMessageResponse response1 = futureResponse1.get(2L, TimeUnit.SECONDS);
            sqsClient.deleteMessage(DeleteMessageRequest.builder().queueUrl(queue.queueUrl()).receiptHandle(response1.messages().get(0).receiptHandle()).build());
            System.out.println(response1);

            futureResponse1 = sqsAsyncClient.receiveMessage(request);
            Thread.sleep(1_000);
            futureResponse1.cancel(true);
            Thread.sleep(1_000);
            snsClient.publish(PublishRequest.builder().topicArn(topic.topicArn()).message("hello2").build());

            CompletableFuture<ReceiveMessageResponse> futureResponse2 = sqsAsyncClient.receiveMessage(request);
            ReceiveMessageResponse response2 = futureResponse2.get(2L, TimeUnit.SECONDS);
            System.out.println(response2);
        }
    }

## Context

For time-sensitive messages, it's impossible to wait for the visibility timeout for a message to be processed by another subscriber.

## Environment

* AWS Java SDK version used: 2.7.29
* JDK version used: 1.8.0(OpenJDK)
* Operating System and version: Ubuntu 18.04.3

**Comment by varunnvs92** [comment]
SDK has no control on the service behavior in terms of closed connections. As you said, it is possible SQS is reading the message and activating visibility timeout before sending the message over the connection (active or closed). I am not sure what SDK can do about it. I will reach out to service team internally and see what their thoughts are.

**Comment by tmartins1** [comment]
I think that too, SDK doesn't have any control over that, but I didn't know a better place to ask for this. Thanks for helping. If you know kind of solution to this please let me know.

**Comment by robin-aws** [comment]
What's happening here is that the buffered client does its own prefetching of messages in the background, independently of the explicit receive message calls made to the client. That means even if you make a single receive call and cancel the future it returned, the client will keep making receive calls to SQS until the client is shut down. This is by design to decrease latency, at the cost of messages sometimes sitting in the local buffers for extra time before being processed. In the extreme case, the visibility timer (which the client tracks itself) may expire before your code ever sees the message, in which case the client will remove it from the buffer.

You can control the visibility timeout the client sets when retrieving messages using this configuration: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/buffered/QueueBufferConfig.java#L476 

You might also be interested the adaptive prefetching feature we just added, which reduces the outgoing calls to SQS when there are fewer incoming calls to the client: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/buffered/QueueBufferConfig.java#L667 With 

However, its a pretty fundamental property of buffering that it can lead to extra local dwell time on messages, because the whole point is to fetch messages independently of the immediate demand for them. You may want to set the visibility timeout to a lower value and use heartbeating via ChangeMessageVisibility to keep it visible for longer once it's actually being processed.

**Comment by dagnir** [comment]
@robin-aws, I believe the question was regarding the V2 SDK specifically, which does not have an equivalent for the buffered client currently.

@tmartins1 Is using the long-polling mechanism from SQS and the low-level async SQS directly.

**Comment by tmartins1** [comment]
I had no idea that messages were prefetched in the background. Now makes sense that messages had to wait for the visibility timeout to be sent to another subscriber. I just think this stuff should be better documented. Thanks for clarifying the behavior.

**Comment by robin-aws** [comment]
My apologies @tmartins1, @dagnir is correct that I misinterpreted the question - I'd spent too much time with the buffered client recently and missed the context I guess. :)

The V2 SDK (and the regular V1 SDK) doesn't do any prefetching. What I said about the buffered client is true, and one of the advantages of using that is if one thread gives up on waiting, a pre-fetched message can be processed by another thread. We do have plans to build a V2-compatible version, but there's no ETA yet.

In general, we recommend that you wait for all outstanding long-polls to complete before shutting down a client, for example. That gives your code the chance to process any messages that might be delivered, even if it just calls ChangeMessageVisibility with a timeout of 0 in order to give other consumers the change to process them.

**Comment by tmartins1** [comment]
@robin-aws if V2 SDK doesn't prefetch any messages, why is the message going to be "in flight" before the second consumer starts receiving?

**Comment by robin-aws** [comment]
There are a few possibilities. As I understand it, the V2 SDK isn't guaranteed to close the connection when the future is cancelled in all cases, as it depends on which underlying HTTP client you're using. Would you be able to trace your code to confirm whether it is or not?

If it is closing the connection, it may be that the service is attempting to deliver a message to a closed connection. I'm going to investigate that on the SQS side and get back to you.

Note that there is always going to be a race condition between the client closing the connection (or turning off message processing) and the service putting a message in flight and returning it, so this is always going to be a possible edge case. It's a best practice to shut down your consumers gracefully, so they can either process messages or make them visible again.

**Comment by dagnir** [comment]
> As I understand it, the V2 SDK isn't guaranteed to close the connection when the future is cancelled in all cases, as it depends on which underlying HTTP client you're using.

Just to clarify on this a little, the Netty client is our only async HTTP client that we ship with the SDK at the moment, and it will close the connection when the request is canceled. But yes, we can't guarantee that this will be the case for all async HTTP clients going forward as it depend on the underlying HTTP library.

**Comment by debora-ito** [comment]
@tmartins1 @robin-aws 

Is there anything further pending from the SDK team on this issue?

**Comment by tmartins1** [comment]
I think so, for what I understood the only solution is to wait for the long polling to finish instead of cancelling the CompletableFuture because doing that can cause undefined behaviour.
