### ISSUE TITLE
Make JSON conversion pluggable

### ISSUE THREAD

**Issue by richarddd** [aws/aws-sdk-java-v2#1527]
The current SDK implementation relies on Jackson for JSON conversion. Although Jackson is very performant it is a huge library.

The big library size makes it less suitable for lambda projects as it affects cold start quite dramatically due to class initialization. The more code there is to load in by java at initialization the longer cold start.

To solve this it would be great if we could have JSON conversion pluggable. Something like:

```kotlin
Json.setMapper(object : JsonConverter {
    val gson = GsonBuilder().create()
    override fun <T> toJson(obj: T) = gson.toJson(obj)
    override fun <T> fromJson(json: String, clazz: Class<T>) = gson.fromJson(json, clazz)
})
```

Internally the SDK could use this mapper function:
`Json.toJson(object)` & `Json.fromJson(jsonData, clazz)`

The default one could be Jackson but it should be pluggable

**Comment by millems** [comment]
We've removed Jackson-databind as a dependency with 2.17.0 and are relying just on Jackson-core and Jackson-dataformat-cbor. I'm not sure if we have a strong reason to make it pluggable, instead of just making the default choice optimal. With the removal of reflection-based unmarshalling is there still a need for this feature request?
