### ISSUE TITLE
How to send file with original name

### ISSUE THREAD

**Issue by mlammdsol** [aws/aws-sdk-java-v2#1589]
I tried running the example on the SDK documentation for S3 Async operations:

public class S3AsyncOps {

    private static final String BUCKET = "sample-bucket";
	private static final String KEY = "testfile.in";

	public static void main(String[] args) {
    	S3AsyncClient client = S3AsyncClient.create();
        CompletableFuture<PutObjectResponse> future = client.putObject(
                PutObjectRequest.builder()
                                .bucket(BUCKET)
                                .key(KEY)
                                .build(),
                AsyncRequestBody.fromFile(Paths.get("myfile.in"))
        );
        future.whenComplete((resp, err) -> {
            try {
                if (resp != null) {
                    System.out.println("my response: " + resp);
                } else {
                    // Handle error
                    err.printStackTrace();
                }
            } finally {
                // Lets the application shut down. Only close the client when you are completely done with it.
                client.close();
            }
        });

It works but the file that for uploaded to S3 is named testfile.in and NOT myfile.in.  How do you specified what name the file will be uploaded as?  Thanks.

**Comment by debora-ito** [comment]
Hi @mlammdsol, the name of the object is the object `KEY` that you specified in the PutObjectRequest. For more info about S3 Objects, check https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

Since this doesn't look like an issue with the SDK itself, I'll go ahead and close it. For general questions about S3 and other AWS services we suggest asking in StackOverflow and the AWS Developer Forums.
