### ISSUE TITLE
DescribeImages but the platform is null otherwise windows

### ISSUE THREAD

**Issue by klonhj2015** [aws/aws-sdk-java-v2#1725]
List<Filter> filters = new ArrayList<Filter>();
		Filter fileter = Filter.builder().name("is-public").values("true").build();
		filters.add(fileter);
		
		DescribeImagesResponse response = ec2.describeImages(DescribeImagesRequest.builder().filters(filters).build());

The Result:
the field platform is null besides winows

**Comment by debora-ito** [comment]
@klonhj2015 According to the EC2 [documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Image.html):

> platform
This value is set to `windows` for Windows AMIs; otherwise, it is blank.

So this is expected. Please check the documentation about EC2 APIs, they contain information and descriptions that might be helpful.

Closing this, feel free to reach out if you have further questions.
