### ISSUE TITLE
Name Query field in GetApiKeysRequest for AWS API Gateway

### ISSUE THREAD

**Issue by hinews** [aws/aws-sdk-java-v2#1732]
Hi, Could you describe how does namequery is working in GetApiKeysRequest for AWS API Gateway?
Does it support special masks? How to get the exact result of the requested API Key by name? Now it returns all keys which names start with "value" but I want only that which equal to this value.

## Describe the issue
Request _GetApiKeysRequest.builder().nameQuery(keyName).build();_ returns all keys started with this name instead of exact API Key that equals to this name.

**Comment by debora-ito** [comment]
@hinews the [documentation](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/apigateway/model/GetApiKeysRequest.html) does not describe options for searching for an exact match, so based on the response of the GetApiKeys API call and seeing it is the same behavior found in the AWS Console > Amazon Api Gateway > API Keys search, I would say this is the expected behavior.

We can definitely improve the documentation to make this more clear, I'll contact the docs team.

**Comment by hinews** [comment]
Hi @debora-ito 

Can I expect for API improvement? For example, by adding an additional parameter in the request like boolean for exact matching?

**Comment by debora-ito** [comment]
I will forward your feedback to the API Gateway team. If they add support for this, it will be available in the SDK.

**Comment by debora-ito** [comment]
There's no public issue tracker, unfortunately. 

The API Gateway team acknowledged the issue and it is now in their backlog, so I'll go ahead and close this. I will update the issue here if there is any change.

**Comment by lin404** [comment]
2 yrs, any update on this?
