### ISSUE TITLE
Get stuck on sending multiple async GetObjectRequest

### ISSUE THREAD

**Issue by squadgazzz** [aws/aws-sdk-java-v2#1788]
## Current Behavior
When I send more than a single async GetObjectRequest, the program gets stuck forever.
I don't have this problem with HeadObjectRequest for example or when the bucket is empty or when I send a single request only.

## Steps to Reproduce (for bugs)
I tried to use Monix scheduler execution context for s3 client with no difference.
Sample code: https://gist.github.com/squadgazzz/476f915f590738c173c84a768498ef90
Output logs: https://gist.github.com/squadgazzz/331dcd6d9204e2bd5fb56fc1286cfabb

## Your Environment
* AWS SDK 2.11.12
* Minio RELEASE.2020-04-10T03-34-42Z
* Scala 2.12
* OpenJDK 8u241

**Comment by Quanzzzz** [comment]
Hi, I tried to reproduce the problem in Java since I’m not familiar with Scala, but I didn’t find anything wrong when I was doing basically the same things as you did in Scala. Here is my java code: https://gist.github.com/Quanzzzz/efdb7b975de6fc0e10c8d8be63e7724a. Please check if there is any logical difference between your code and mine. If not, then probably it’s a Scala specific issue.

**Comment by jfz** [comment]
I'm seeing somewhat similar behavior with Scala application: Scala 2.13.2, Java 11, sdk 2.13.6. The future returned by putObject sometimes never finishes for about 1% of all the requests. I have to put an timeout and retry from application side to get around it, but I'm still concerned about there're might be some resource leak somewhere in cases like this.

[Sample Code](https://github.com/Netflix-Skunkworks/iep-apps/blob/9d44ea810076f9d4cb9879d52a19636a2f098c01/atlas-persistence/src/main/scala/com/netflix/atlas/persistence/S3CopySink.scala#L178)
