### ISSUE TITLE
Use http_proxy enviroment variable for ProxyConfiguration

### ISSUE THREAD

**Issue by Jakob-em** [aws/aws-sdk-java-v2#1793]
## Describe the Feature
The ProxyConfiguration should take the values from the http_proxy/https_proxy environment variables. As seen here: https://github.com/aws/aws-sdk-java/issues/1959

## Is your Feature Request related to a problem?
I was running into some issues when using a proxy for the connection to s3 and then realised that the system http_proxy was not used for the connection.

- [ ] I may be able to implement this feature request

**Comment by debora-ito** [comment]
Thank you for reaching out @Jakob-em. This is a reasonable ask, since it's supported in V1.

**Comment by mjeffrey** [comment]
We just had the same issue for KMS (we use "https" rather than "http":

`-Dhttps.proxyHost` and  `-Dhttps.proxyPort`

Appears to be in the  ProxyConfiguration.resolvePort() and ProxySystemSetting.

If both `https.proxy*` and `http.proxy*` are set then you should prefer the https values (I assume all calls are https 😃  ). 

A workaround is to set the `http.proxy*` properties as well.
