### ISSUE TITLE
Allow reuse of AwsCredentialsProvider implementations

### ISSUE THREAD

**Issue by marko-asplund** [aws/aws-sdk-java-v2#1835]
AWS Java SDK v2 users sometimes need to create custom credentials provider implementations.
While the `AwsCredentialsProvider` interface makes this possible, being able to reuse code in the SDK's concrete implementations of this interface, would make customization much easier.

## Describe the Feature
Allow subclassing concrete `AwsCredentialsProvider` implementations (e.g. `InstanceProfileCredentialsProvider` et al.) included in the AWS Java SDK v2 by removing the `final` keyword from class declaration.

Also, being able to reuse credentials provider `BuilderImpl`s such as
`software.amazon.awssdk.auth.credentials.HttpCredentialsProvider.BuilderImpl` would also be helpful.

## Is your Feature Request related to a problem?
I'm facing a concrete issue described in this ticket: https://github.com/jtblin/kube2iam/issues/241
With the changes described in this feature request I'd be able to implement my a custom version of `InstanceProfileCredentialsProvider` that would use IMDSv1.

## Proposed Solution
See above.

## Additional Context

Please see issue https://github.com/jtblin/kube2iam/issues/241

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used: 2.11.12
* JDK version used: Java 11
* Operating System and version: N/A

**Comment by zoewangg** [comment]
Hi @marko-asplund thanks for reaching out, unfortunately, the class is `final` by design because it is not intended to be subclassed, and it is not designed for inheritance.

**Comment by marko-asplund** [comment]
Thanks for your reply @zoewangg !

Would it then be possible to allow code reuse by using some other mechanism to make implementing custom credentials providers easier? Subclassing just seemed like a natural way to do it.

Also, I'd like to understand the rationale behind preventing subclassing in this case a bit better. I mean implementing custom credentials providers is still "supported", right? Users can still e.g. build their own custom AWS SDK versions from source or use tools to tweak the bytecode to allow subclassing.

**Comment by zoewangg** [comment]
Apologies for the delayed response. 

Yes, customers are still able to copy paste the code to their own credential providers. The difference here is that by disallowing subclassing, we don't need to maintain backwards-compatibility for our internal implementations. If we "opened" that class, changes like renaming a protected method would be impossible because it might break customers who overrode that method.

In general, we favor composition over inheritance in our projects, so most of the concrete classes in the SDK are not designed for inheritance.

Per recommendations from `Effective Java`,
> Item 17: Design and document for inheritance or else prohibit it

we declared all SDK public concrete classes `final` to prevent subclassing.

Hope that answers your question. :)
