### ISSUE TITLE
Unnecessary passing of item class

### ISSUE THREAD

**Issue by amitoh** [aws/aws-sdk-java-v2#1853]
There is an unused argument in the update request object making it hard to use in a generic context (when Ts class is unknown at compile time)

https://github.com/aws/aws-sdk-java-v2/blob/24f99c8a7bcc545e6f3fffcc75c460a94b870be9/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/UpdateItemEnhancedRequest.java#L54

**Comment by amitoh** [comment]
A workaround could be something like:
UpdateItemEnhancedRequst.<T>builder(null)

**Comment by bmaizels** [comment]
Hi @amitoh,

We designed the interface this way to make it slightly more intuitive for people feeling their way around the interface to get type-safety in a fluent and discoverable way. Our initial iteration of the code simply had no arguments, but because of the builder chain it forced people to write code like this :

```
UpdateItemEnhancedRequest.<MyItem>builder().item(myItem).build();
```

The issue here was that the IDE didn't really help you much it would happily lead you down the dead-end where you had:

```
UpdateItemEnhancedRequest.builder().item(
```

and then would not accept any concrete inferred type for the item because it had already committed to an unknown capture type on builder().

If the type is really not known, then could you use Object as a workaround? Eg:
```
UpdateItemEnhancedRequest.builder(Object.class).item(unknownItem).build()? You would then be responsible for the unsafe but permissible cast to UpdateItemEnhancedRequest<ActualType> later, as presumably you'd have a strongly typed TableSchema to use it with somewhere.
