### ISSUE TITLE
DynamoDB Enhanced Client: Query call limits

### ISSUE THREAD

**Issue by hinews** [aws/aws-sdk-java-v2#2003]
Hi, in AWS documentation written that Query returns only 1 Mb per call.
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.Pagination.html

> Query
> The result set from a Query is limited to 1 MB per call. You can use the LastEvaluatedKey from the query response to retrieve more results.
> 

But the response object in DynamoDB Enhanced Client doesn't contain LastEvaluatedKey field. Would this call work as expected if table will have much that 1 Mb data to return:

```
AttributeValue tokenTypeAttValue = AttributeValue.builder().s(tokenType.name()).build();
Expression expression = Expression.builder()
                    .expression("tokenType = :value")
                    .putExpressionValue(":value", tokenTypeAttValue)
                    .build();

QueryConditional queryConditional = QueryConditional
                    .keyEqualTo(Key.builder().partitionValue(runtimeVars.tenantName).build());

return table().query(builder -> builder.consistentRead(true)
                    .queryConditional(queryConditional)
                    .filterExpression(expression))
                    .items().stream().parallel().collect(Collectors.toList());
```

method table() returns DynamoDbTable object.

The second question is related to the filterExpression. How can I specify my filter in query itself to not cause increased read capacity units in the code snippet above? I didn't find how to specify these conditions as described in documentation: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#API_Query_RequestSyntax

> DynamoDB calculates the number of read capacity units consumed based on item size, not on the amount of data that is returned to an application. The number of capacity units consumed will be the same whether you request all of the attributes (the default behavior) or just some of them (using a projection expression). The number will also be the same whether or not you use a FilterExpression.

**Comment by debora-ito** [comment]
Hi @hinews. For question 1, the 1 MB size limit is for each page. `table().query()` returns a [PageIterable](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/PageIterable.html), and calling `items()` on the result of the query will return an iterable to iterate through the paginated items across all response pages. You don't have to worry about the LastEvaluatedKey because the pagination is automatic in this case.

For question 2, the note you quoted in the description is saying that providing a filter expression or a projection expression will not reduce the number of read capacity because "the number of read capacity units consumed is based on item size, not on the amount of data that is returned to an application". One reason for this is that FilterExpression is applied after a Query finishes, but before the results are returned.

Let us know if that helps.

**Comment by hinews** [comment]
Hi @debora-ito 

Thanks for your help. Could you describe is it possible to apply filter expression in the query itself, I just need to reduce results by setting only one filter but need to do it on query stage to reduce item size and read capacity units before

**Comment by debora-ito** [comment]
Query runs are based on primary keys, so you'll need to plan your table structure if you want to optimize costs of read capacity units consumed. I found some posts on the subject that might be helpful:
- Best Practices for Designing and Using Partition Keys Effectively (from the DynamoDB [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html))
- How to use DynamoDB global secondary indexes to improve query performance and reduce costs ([post](https://aws.amazon.com/blogs/database/how-to-use-dynamodb-global-secondary-indexes-to-improve-query-performance-and-reduce-costs/) from AWS Blog )
- Optimize Amazon DynamoDB scan latency through schema design ([post](https://aws.amazon.com/blogs/database/optimizing-amazon-dynamodb-scan-latency-through-schema-design/) from AWS Blog)

**Comment by debora-ito** [comment]
If there's no other question, this issue will close soon. If you have any other question just add in the comments.

**Comment by user20161119** [comment]
Enhanced client not support query on global second index?
