### ISSUE TITLE
DELETE shadow using dataplane sdk, version number is not getting reset

### ISSUE THREAD

**Issue by nageswararao-boddu** [aws/aws-sdk-java-v2#2134]
HI,
I am trying to delete a specific shadow using dataplane-sdk as below. After deleting the shadow, i am getting 404 as expected while querying the same shadow. But when creating same shadow again, the shadow version number is not getting reset to 1, instead its taking previous version number and getting incremented.

ThingShadowRequest deleteThingShadowRequest = DeleteThingShadowRequest.builder().thingName(thingName).shadowName(subShadowName).build();
                    DeleteThingShadowResponse deleteThingShadowResponse = awsIotDataPlaneClientInstanceHolder.getIotDataPlaneClient().deleteThingShadow(deleteThingShadowRequest);

<dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>iotdataplane</artifactId>
            <version>2.14.1</version>
 </dependency>

Thanks,
Nages

**Comment by debora-ito** [comment]
@nageswararao-boddu I'd say this behavior is expected. The Developer Guide [documentation](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-data-flow.html#deleting-thing-data) mentions something about shadow version slightly:
> Setting the device's shadow state to null does not delete the shadow. The shadow version will be incremented on the next update.

And I see the same behavior when using the AWS IoT console.

**Comment by nageswararao-boddu** [comment]
@debora-ito I'm not setting the state to null, instead I'm deleting whole shadow. From documentation, 
> Setting the device's shadow state to null does not delete the shadow. The shadow version will be incremented on the next update.
SO in this case its complete delete.

**Comment by debora-ito** [comment]
I understand, but I still think both cases are related in the logic of the shadow version. Since shadow name is used as an identifier (meaning, to retrieve a shadow with `getThingShadow` you provide a thing name and a shadow name, there's no other unique identifier like shadow id), deleting and recreating the shadow with the same name would be considered an update and the version number would be incremented, specially if I have the option of using optimistic locking. 

I'll reach out to the iot dataplane service team to confirm if this is the case, and if it is I'll ask to add a note to their documentation.

**Comment by debora-ito** [comment]
@nageswararao-boddu I've got confirmation from the IoT service team that this behavior is expected.

I've asked them to make it more clear in the documentation. I'll close this for now, as there's no issue with the SDK, but feel free to reach out if you have further questions.
