### ISSUE TITLE
How to get the Serial Number or UUID of EC2 instance by Java SDK?

### ISSUE THREAD

**Issue by lynch0571** [aws/aws-sdk-java-v2#2137]
## Describe the issue
There's no Serial Number or UUID field in the DescribeInstancesResponse.

And there's no Serial Number or UUID in the [document](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Instance.html).

**Comment by debora-ito** [comment]
Do you mean something that is not the `instanceId`? Can you give us some context?

**Comment by lynch0571** [comment]
The instanceId is not what I want.I'm looking for the Serial Number.For example:
ec27b105-b16d-xxxx-xxxx-1906b8fb9eb5
You can execute shell command to get it:
`dmidecode -s system-serial-number`
or
`dmidecode -t system`

**Comment by debora-ito** [comment]
`dmidecode` is a tool that reports information about your system's hardware as described in your system BIOS. Since it's hardware information I don't think you will get the system serial number or uuid from an EC2 API. Using the `dmidecode` command is the recommended way in the [User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html).

I'll go ahead and close this. Feel free to reach out if you have further questions.

**Comment by lynch0571** [comment]
Thank you
