### ISSUE TITLE
No examples of Query partition and sort key using Dyanmodb Enhanced client 

### ISSUE THREAD

**Issue by tkindra2** [aws/aws-sdk-java-v2#2143]
The example code and documentation does not provide example of how to query table or index with sort key. I am looking for example where key=X and sort key between A and B. This seems like basic use case but i have spent hours trying to figure out.

## Describe the issue
If you look at example below and assume the sort key is regDate. how will you query Id= X and regDate between 2020-01-01 and 2020-11-01?

https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedQueryRecords.java

**Comment by debora-ito** [comment]
Hi @tkindra2 thank you for reaching out. Here's an example for a query expression using _between_:

```java
DynamoDbTable<Customer> mappedTable = enhancedClient.table("Customer", TableSchema.fromBean(Customer.class));

Key fromKey = Key.builder().partitionValue("X").sortValue("2020-01-01").build();
Key toKey = Key.builder().partitionValue("X").sortValue("2020-11-01").build();

QueryConditional sortValueInBetween = QueryConditional.sortBetween(fromKey, toKey);

Iterator<Customer> results = mappedTable.query(sortValueInBetween).items().iterator();
```

Note that here I'm using `regDate` as the sort key because you asked, but in the the `Customer` table of the `aws-doc-sdk-examples` the sort key is `CustName`.

I'll work to add this example to the EnhancedQueryRecords example you referenced. Let us know if this helps.

**Comment by debora-ito** [comment]
This example was added to the AWS docs SDK examples repo - 

https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/EnhancedQueryRecordsWithSortKey.java
