### ISSUE TITLE
S3 Generic Exception for Glacier Restore In-Progress

### ISSUE THREAD

**Issue by nitrag** [aws/aws-sdk-java-v2#2272]
An "In Progress" retrieval of object from S3 Glacier (`restoreObject()`) should not throw a S3 Generic Exception.

## Describe the Feature
Either:
 - Create specific S3 Exception for "In Progress" (GlacierRestoreInProgressException)
 - Create a strongly typed enum for each of the types of responses . For instance:

```kotlin
enum class GlacierRestoreStatus {
            CREATED,
            IN_PROGRESS,
            COMPLETED,
            FAILED
        }
```
## Is your Feature Request related to a problem?
Well it certainly makes for unclean code where I have to parse the statusCode in two places. Once if it's not an exception and again if it is.

## Proposed Solution
See Describe and below

## Describe alternatives you've considered
Messy code.

## Additional Context

I've created a method for retrieving an object for glacier. It will either create the request or return in-progress, completed, failed.

```kotlin
try {
    val result = s3client.restoreObject(restoreObjectRequest)
    when (val statusCode = result.sdkHttpResponse().statusCode()) {
        200 -> {
            logger.info("Glacier object thawed successfully: $bucket/$key")
            GlacierRestoreStatus.COMPLETED
            }
        }
        202 -> GlacierRestoreStatus.CREATED
        409 -> GlacierRestoreStatus.IN_PROGRESS  // will not reach, throws generic exception instead
        else -> {
            logger.error(
                "Glacier Restore failed: ${result.sdkHttpResponse().statusText()} " +
                "(HTTP Response Code: $statusCode")
            GlacierRestoreStatus.FAILED
        }
    }
}catch (e: S3Exception) {
    return if(e.statusCode() == 409){
        GlacierRestoreStatus.IN_PROGRESS
    } else {
        logger.error("Failed to transition resource from Glacier: ${e.localizedMessage}")
        GlacierRestoreStatus.FAILED
    }
}
```

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used: `2.15.0`
* JDK version used: `11`
* Operating System and version: `docker + linux`

**Comment by debora-ito** [comment]
Hi @nitrag, 

S3 `restoreObject` creates a request to restore the object to a Frequent Access tier and this operation takes some time, so if you call a `restoreObject` again on the same object S3 sends a status code `409 Conflict` error because a request already exists. S3 cannot change this behavior and send a different exception like you suggested, it would be a breaking change. Besides, a different exception would still be an exception, it would not reach the try block.

The recommended way to check the status of the restorations is sending a HEAD request, as mentioned in the [API reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_RestoreObject.html):

> To get the status of object restoration, you can send a HEAD request. Operations return the x-amz-restore header, which provides information about the restoration status, in the response. You can use Amazon S3 event notifications to notify you when a restore is initiated or completed. For more information, see [Configuring Amazon S3 Event Notifications](https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html) in the Amazon Simple Storage Service Developer Guide.

Let us know if this helps.
