### ISSUE TITLE
RequestBody.fromInputStream with optional contentLength

### ISSUE THREAD

**Issue by brackxm** [aws/aws-sdk-java-v2#2431]
contentLength is optional in RequestBody.
But when creating a RequestBody from an InputStream a contentLength is required.

## Expected Behavior
Allow easy creation of a RequestBody from an InputStream without contentLength.

## Current Behavior
When creating a RequestBody from an InputStream a contentLength is required, due to the parameter being a long.

## Possible Solutions

* change signature of RequestBody.fromInputStream to accept a Long
* add a method without contentLength
* add a utility to create a ContentStreamProvider from an InputStream (like in RequestBody.fromInputStream)

## Steps to Reproduce (for bugs)
RequestBody.fromInputStream(body, null)
RequestBody.fromInputStream(body)

## Context
S3Client.putObject from an InputStream without knowing the contentLength in advance

## Your Environment
* AWS Java SDK version used: 2.16.43

**Comment by debora-ito** [comment]
Hi @brackxm. Providing `content-length` upfront is a restriction on the S3 side, the PutObject API requires the `content-length` header.

This is an old ask we get since the Java SDK v1. It will probably be addressed in the v2 version of TransferManager, which we are keeping track of in https://github.com/aws/aws-sdk-java-v2/issues/37. Closing this.

**Comment by brackxm** [comment]
a workaround is to use RequestBody.fromInputStream as a utility to create a ContentStreamProvider only
