### ISSUE TITLE
Add API call Error metric to AWS SDK metrics

### ISSUE THREAD

**Issue by HimalayPatel** [aws/aws-sdk-java-v2#2711]
Currently the list of AWS SDK metrics includes the following metrics: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics-list.html. This includes a metric for the successful API calls (ApiCallSuccessful) but not for the failed ones. There is also not a TotalApiCalls metric that would enable calculating the failed calls. 

## Describe the Feature
This new error metric will cover all and only the failed API calls. This covers all AWS APIs. Adding this metric to the ApiCallSuccessful metric should result in the total API calls made for that API. This metric will be a blanket metric covering all cases that led to call failure (eg. client timeout, client side request error, service logic error, client side response error, etc.)

## Is your Feature Request related to a problem?
We are using multiple AWS services some of which are critical for our service to function correctly. Hence having availability metrics for these services is crucial.

## Proposed Solution
N/A

## Describe alternatives you've considered
A simple metric for TotalApiCalls should even work, as failed calls would be easy to calculate from that.

- [not sure ] I may be able to implement this feature request

## Your Environment
* AWS Java SDK version used: v2
* JDK version used: 1.8
* Operating System and version: Amazon Linux 2

**Comment by debora-ito** [comment]
Hi @HimalayPatel thank you for reaching out.

The ApiCallSuccessful metric is generated for each request, it's "true" if the API call was successful and "false" otherwise.  
This means that you can obtain the number of failed calls by using aggregations.

If you are using CloudWatch, you can visualize the number of failed calls by using CloudWatch expressions, here's one example using the CloudWatch console:

![Screen Shot 2021-09-16 at 6 12 01 PM](https://user-images.githubusercontent.com/476307/133711587-52da65d9-61aa-4669-85f7-af7852d5dd3d.png)


1. In the All Metrics menu, choose the "ApiCallSuccessful" to be added to the graph
2. In the Graphed Metrics tab, choose the "Sample Count" statistic
3. Duplicate the metric you created in the step 2, change the statistic to "Sum"
4. Create a new metric by clicking in Math Expression, and use subtraction:  "Sample Count" - "Sum". The "Sum" expression will sum up all the successful calls. Subtracting the successful calls from the total sample gives you the total of failed calls.


For the TotalApiCalls metric you've requested, this is obtained by the Sample Count aggregation in CloudWatch.
For adding Exception metric support, we have a feature request to add that, tracking here: https://github.com/aws/aws-sdk-java-v2/issues/2485

Let us know if this helps.

**Comment by HimalayPatel** [comment]
Hi @debora-ito, thanks for the explanation! It seems that I am seeing some regular failures (along with the failure count), but that's another topic.

<img width="1501" alt="Screen Shot 2021-09-30 at 5 09 17 PM" src="https://user-images.githubusercontent.com/12826166/135546615-5ef88336-8667-431f-8b0b-5dfb9e591d9b.png">
