### ISSUE TITLE
Async requests that complete when the operation is complete

### ISSUE THREAD

**Issue by cjkent** [aws/aws-sdk-java-v2#286]
The behaviour of the existing asynchronous clients is surprising and not particularly useful in a number of cases. When requesting a long-running operation, the async request completes when the operation is _started_, not when it completes.

I've seen this when creating or updating a CloudFormation stack and when making changes to DynamoDB tables. The async request completes while the AWS resources are still being modified.

This  behaviour means I still need to poll the resources to figure out when the update is finished. This completely defeats the point of using an async API. What I actually want is for the async request to complete once the resources have been updated and are ready to use.

**Comment by millems** [comment]
The async clients are currently just a non-blocking proxy for the underlying service APIs. We're still limited by the fact that the underlying service API is asynchronous (eg. the dynamo create-table API: http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html).

In 1.11.x there is a concept called waiters that handles the polling on your behalf (see https://github.com/aws/aws-sdk-java-v2/issues/24 and https://github.com/aws/aws-sdk-java-v2/issues/84 for adding similar features in V2), but that's still just hiding the polling from you. 

Would the polling implementation of waiters fix your problem, or would you want a push-based system where the SDK opens a port on your application and listens for a notification from AWS notifying you of the completion? There's a lot of tricky issues with that, so we've stuck to polling so far, but having more datapoints in favor of push-based notifications would be great feedback.

**Comment by cjkent** [comment]
I wasn't aware of waiters, thanks for the tip. They do what I would expect the async operations to do but with a pretty unpleasant API.

I'm fine with polling behind the scenes. What I'd really like to see is an async client with methods returning a `CompletableFuture` that completes when the resource is in the requested state.

If the async clients worked that way (which I'd argue is the way most people would expect them to work) then there would be no need for waiters.

**Comment by millems** [comment]
That's great feedback! The 1.11.x waiter API is a bit complicated and doesn't really look like the rest of the SDK. I'm hoping we can fix that and make it a bit easier to find.

It would be tricky to make the default behavior to wait for creation. That would make it backwards incompatible to add a waiter to an existing operation, deviate from the sync behavior and other language SDKs, and not line up with the service-specific documentation.

If you have the time, it would be a huge favor to us if you could answer some of these questions to help us when we redesign the 2.0 waiters:

1. At what point did you notice that CreateTable didn't wait for completion?
2. After noticing that, what all did you do to find how to get the behavior that you initially expected? (Details really help: did you try something? look somewhere? ask someone?)
3. Other than making it the default behavior, what would your ideal syntax be for waiters? How would you want to tell the SDK you want to wait for the table to finish being created?

**Comment by cjkent** [comment]
1) When we first started writing tests for our Dynamo code. They failed because the tables didn't exist.
1) We read the API docs for the table creation operations on the client and async client. Nobody spotted the `waiters()` method. Presumably because it's surprising to have that functionality separate from the operations.
1) My ideal design would be to have new clients with a similar API to the existing async client. i.e. every operation would return a `CompletableFuture`. But the semantics would be different - the future would complete when the resource entered the requested state and it would complete exceptionally if the operation failed. So the future returned from `createTable()` would complete when the table was ready to use. Unfortunately I can't think of an alternative API that would be intuitive.

The fundamental problem is illustrated by the API docs for `AmazonDynamoDBClient`. From the class description:

> Client for accessing DynamoDB. All service calls made using this client are blocking, and will not return until the service call completes.

From the docs for `createTable`:

> CreateTable is an asynchronous operation. Upon receiving a CreateTable request, DynamoDB immediately returns a response with a TableStatus of CREATING.

This is a fundamentally confused and confusing API. It claims to be blocking but contains methods that it describes as asynchronous.

In addition, having an asynchronous version of this API makes very little sense. What is the point of having `createTableAsync` when `createTable` is already asynchronous and returns immediately? Now we have two different ways of asynchronously invoking that operation and no simple way to do it synchronously.

**Comment by millems** [comment]
That's super helpful, thanks!

We can definitely improve the javadoc so it doesn't sound like it is contradicting itself. Your answers give great insight into how our APIs are thought about. It's sometimes a curse to be so close to them.

The advantage to the async version of the `CreateTable` API is that it's entirely non-blocking. The sync version of the `CreateTable` API will block the calling thread while it communicates with DynamoDB. The async version will never block the calling thread, so it's better for high-throughput applications that want to run on fewer threads. The top answer on this stack overflow topic can explain it much better than I can: https://stackoverflow.com/questions/8546273/is-non-blocking-i-o-really-faster-than-multi-threaded-blocking-i-o-how

One of the most confusing things here is that there's two 'levels' of asynchronous, but we're not explaining them well and it ends up being surprising: 
1. The Dynamo DB **service** API is asynchronous. It won't hold open the connection to the client while it creates the table because it will take a very long time. The client and the service have connection limits, so not holding a connection open for a few minutes while it is created is much more scalable for both parties.
2. The Dynamo DB **client** API is either synchronous or asynchronous. The async client won't hold the calling thread while it makes the service call because it will take a long time (relative to the work that thread could be doing in the meantime). The client application has thread limits and overhead from context switching, so not holding the thread for a few hundred milliseconds when it could be doing other work is more scalable for the client when the client is handling a very large number of concurrent requests.

We'll talk about having a separate 'waiting' client, but it might be tricky to expose in a meaningful way. If we could come up with a good method name, how about if we added the waiter method to the existing clients with the same method prefix so that it shows up in the IDE when you do `dynamodb.createTable`?

```Java
CompletableFuture<CreateTableResponse> createdResponse = 
        dynamoDb.createTableAndWaitUntilExists(createTableRequest);
```

We'll definitely need to work on the name, but it might prevent people from being surprised that the `createTable` API doesn't wait. We'd also refer to this method in the `createTable` javadoc.

**Comment by cjkent** [comment]
I understand the difference between the two client APIs. But for my purposes the difference is so small that it's irrelevant. I'm not creating Dynamo tables or deploying CloudFormation stacks in a tight loop in performance critical code, and I suspect that is true for a lot of your users.

The existing asynchronous API optimises for performance at the expense of usability. And the synchronous API doesn't really optimise for anything. It's not terribly nice to use and it has worse performance than the async API. What seems to be missing is an API that optimises for simplicity ease-of-use, and that's what I think I'm asking for.

Creating separate methods on the existing clients that wait for the operation to complete on the server would work, but I wonder if the API would be a bit much. `CompletableFuture` provides an example of this:

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html

Most operations have a regular and at least one async version, and in some cases two async versions. It's hard to skim the API and see what you can do with it because of the sheer number of methods.

**Comment by millems** [comment]
This is great feedback because we're getting a different perspective on sync vs async.

To me:
1. The sync clients optimize for latency and ease of use. They're optimally used in the common one-thread-per-request service model. Most customers use these clients.
2. The async clients optimize for throughput, but are a bit trickier to use. They're optimally used in threading models where a single thread or a handful of threads are processing many concurrent requests/events.

> the synchronous API doesn't really optimise for anything.

From this it sounds like we're missing our mark on making the sync clients easy to use for users like you. 

> I wonder if the API would be a bit much

We agree that too many methods on a client is a risk, and we're trying to be careful not to overdo it. On the good side, there aren't terribly many operations that are performed asynchronously on the service side that require the client to wait. On the bad side, that means when people do run into them, it's a surprise.

Aside: My opinion is that it would be nice to be able to use more of a resource model for our APIs  (`dynamo.table("name").create()` instead of `dynamo.createTable("name")`) to make our clients less intimidating, but we aren't able to do that because of limitations in the way we model the APIs.

> What seems to be missing is an API that optimises for simplicity and ease-of-use, and that's what I think I'm asking for.

Are there other areas where you think we could improve simplicity/ease of use?

**Comment by rleibman** [comment]
In order to solve this problem in scala I have a little utility:
```
  def whileInProgress[Request <: AmazonWebServiceRequest, Response](
      method: Request => java.util.concurrent.CompletableFuture[Response],
      request: Request,
      isInProgress: Response ⇒ Boolean,
      duration: Duration = 30 seconds)(implicit actorSystem: ActorSystem): Future[Response] = {

    import actorSystem.dispatcher
    val log = Logging(actorSystem, getClass)

    def loop(): Future[Response] = {
      val fut = method(request).toScala
      fut.flatMap { response =>
        if (isInProgress(response)) {
          log.debug(s"Request ${request.getClass.getName} in progress: ${response}")
          Thread.sleep(duration.toMillis)
          loop
        } else {
          Future.successful(response)
        }
      }
    }

    loop
  }
```
This lets you specify for every operation a different function that checks to see if you're done. I use it specifically for CloudFormation stack creation, I imagine you could write something similar in java.

**Comment by millems** [comment]
We added waiters to 2.x last year, which should resolve the majority of these issues. Is this feature request still relevant? If so, what specifically can still be improved?

**Comment by yasminetalby** [comment]
Hello all,

Let us know if this feature-request is still relevant or if you have any improvement request.

We appreciate your feedback and contribution to improving the AWS Java SDK V2.

Sincerely,

Yasmine
