### ISSUE TITLE
DynamoDB EnhancedAttributeValue "set" operations should accept sets

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#3453]
### Describe the feature

DynamoDB supports "set" types for homogenous multi-valued data, and the `EnhancedAttributeValue` type provides mapper methods for those (e.g., `fromSetOfNumbers`). However, the signatures of those methods accept specifically `List`. Instead, they should accept `Collection`.

### Use Case

I would like to pass an actual `Set` implementation to `fromSetOf*`.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.17.284

### JDK version used

AdoptOpenJDK-11.0.11+9

### Operating System and version

Gentoo Linux

**Comment by yasminetalby** [comment]
Hello @chrylis ,

Thank you very much for your submission.
The **Set Types** ([NS, BS and SS type](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html)) are all defined as list by the API [see](https://github.com/aws/aws-sdk-java-v2/blob/master/services/dynamodb/src/main/resources/codegen-resources/dynamodb/service-2.json#L4073) hence why the SDK accept list specifically for those method.
This would be more of a service behavior rather than an SDK behavior feature request.

Best,

Yasmine

**Comment by chrylis** [comment]
[The DynamoDB documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html) explicitly says that the set types display set semantics, not list semantics: 

> Each value within a set must be unique. The order of the values within a set is not preserved.

**Comment by yasminetalby** [comment]
Hello @chrylis ,

Update: The team has discussed the feature-request and has added it to the backlog.
There will be an update posted on this issue once the feature-request is implemented.

Thank you very much for your submission and collaboration.

Sincerely,

Yasmine.
