### ISSUE TITLE
DefaultSdkHttpFullRequest, host, port and encodedPath with wrong values for the Signed URL from bucket with Amazon S3 Transfer Acceleration enabled

### ISSUE THREAD

**Issue by rl1m4** [aws/aws-sdk-java-v2#3537]
### Describe the bug

If we want the `S3Presigner.presignPutObject` to create the `presigned url` pointing to the `accelerated s3 bucket` endpoint, `https://host:portNumber/{bucket_name}.s3-accelerate.amazonaws.com/file-id`, then we have to instantiate the S3PreSigner like this:

```
S3Presigner.builder()
   .region(region)
   .serviceConfiguration(
       S3Configuration.builder()
           .accelerateModeEnabled(true)
           .checksumValidationEnabled(false)
           .build()
   )
   .build()
```
It will produce signed URLs with the "s3-accelerate" domain part but it overrides the `host`, `port` and `encodedPath`:

URL without transfer acceleration enabled:

`http://localhost:port-number/bucket-name/file-id?X-Amz-Algorithm=example&X-Amz-Date=example&X-Amz-SignedHeaders=host&X-Amz-Expires=example&X-Amz-Credential=local&X-Amz-Signature=example`

The `PresignedRequest`:
```
DefaultSdkHttpFullRequest(
   httpMethod=PUT, 
   protocol=http, 
   host=localhost, 
   port=56831, 
   encodedPath=/bucket-name/file-id, 
   headers=[Expect, Host], 
   queryParameters=[X-Amz-Algorithm, X-Amz-Date, X-Amz-SignedHeaders, X-Amz-Expires, X-Amz-Credential, X-Amz-Signature]
)
```
`host value: localhost:port-number`

URL with transfer acceleration enabled:
`http://bucket-name.s3-accelerate.amazonaws.com/file-id?X-Amz-Algorithm=example&X-Amz-Date=example&X-Amz-SignedHeaders=host&X-Amz-Expires=example&X-Amz-Credential=local&X-Amz-Signature=example`

The `PresignedRequest`:
```
DefaultSdkHttpFullRequest(
   httpMethod=PUT, 
   protocol=http, 
   host=bucket-name.s3-accelerate.amazonaws.com, 
   port=80, 
   encodedPath=file-id, 
   headers=[Expect, Host], 
   queryParameters=[X-Amz-Algorithm, X-Amz-Date, X-Amz-SignedHeaders, X-Amz-Expires, X-Amz-Credential, X-Amz-Signature]
)
```
`host value: bucket-name.s3-accelerate.amazonaws.com`

### Expected Behavior

The `PresignedRequest`, `host` and `URL` to remain similar structure as with transfer acceleration disabled but appending the `s3-accelerate.amazonaws.com` after `bucket-name`:

`http://localhost:port-number/bucket-name.s3-accelerate.amazonaws.com/file-id?X-Amz-Algorithm=example&X-Amz-Date=example&X-Amz-SignedHeaders=host&X-Amz-Expires=example&X-Amz-Credential=local&X-Amz-Signature=example`

The `PresignedRequest`:
```
DefaultSdkHttpFullRequest(
   httpMethod=PUT, 
   protocol=http, 
   host=localhost, 
   port=56831, 
   encodedPath=/bucket-name.s3-accelerate.amazonaws.com/file-id, 
   headers=[Expect, Host], 
   queryParameters=[X-Amz-Algorithm, X-Amz-Date, X-Amz-SignedHeaders, X-Amz-Expires, X-Amz-Credential, X-Amz-Signature]
)
```
`host value: localhost:port-number`

### Current Behavior

The `PresignedRequest`, `host` and `URL` structure with transfer acceleration enabled are changing to:

`http://bucket-name.s3-accelerate.amazonaws.com/file-id?X-Amz-Algorithm=example&X-Amz-Date=example&X-Amz-SignedHeaders=host&X-Amz-Expires=example&X-Amz-Credential=local&X-Amz-Signature=example`

The `PresignedRequest`:
```
DefaultSdkHttpFullRequest(
   httpMethod=PUT, 
   protocol=http, 
   host=bucket-name.s3-accelerate.amazonaws.com, 
   port=80, 
   encodedPath=file-id, 
   headers=[Expect, Host], 
   queryParameters=[X-Amz-Algorithm, X-Amz-Date, X-Amz-SignedHeaders, X-Amz-Expires, X-Amz-Credential, X-Amz-Signature]
)
```
`host value: bucket-name.s3-accelerate.amazonaws.com`

### Reproduction Steps

`S3Presigner`
```
S3Presigner.builder()
    .region(region)
    .serviceConfiguration(
        S3Configuration.builder()
             .accelerateModeEnabled(true)
             .checksumValidationEnabled(false)
             .build()
     )
    .build()
```

```
S3AsyncClient.builder()
     .region(region) 
     .serviceConfiguration(S3Configuration.builder().accelerateModeEnabled(true).build())
     .build()
```

### AWS Java SDK version used

awssdk:s3:2.17.158

### JDK version used

openjdk version "11.0.7"

### Operating System and version

Linux AMD64 Docker

**Comment by yasminetalby** [comment]
Hello @rl1m4 ,

Thank you very much for your submission.

This seems like the expected behavior.

Using [.accelerateModeEnabled(true)](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Configuration.Builder.html#accelerateModeEnabled(java.lang.Boolean)) enables using the accelerate enedpoint when accessing S3. Accelerate endpoints allow faster transfer of objects by using Amazon CloudFront's globally distributed edge locations.

As per the the [Amazon S3 Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-getting-started.html) documentation, the following are part of the requirement for using Transfer Acceleration on an S3 bucket:
- Transfer Acceleration is only supported on virtual-hosted style requests. For more information about virtual-hosted style requests, see [Making requests using the REST API](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAPI.html).
- To access the bucket that is enabled for Transfer Acceleration, you must use the endpoint bucketname.s3-accelerate.amazonaws.com. Or, use the dual-stack endpoint bucketname.s3-accelerate.dualstack.amazonaws.com to connect to the enabled bucket over IPv6.

Is there a reason why you are excepting a different behavior?

Best,

Yasmine
