### ISSUE TITLE
Timeout because killing too many threads using SQSClien

### ISSUE THREAD

**Issue by nikskushwah** [aws/aws-sdk-java-v2#3556]
### Describe the bug

I'm using 2.17.239 of the SQS Java SDK.

The application I'm working on has multiple threads using one instance of the SqsClient.  Sometimes we interrupt these threads.  If enough threads get interrupted we start seeing "Unable to execute HTTP request: Timeout waiting for connection from pool".  This occurs once we've had 20 threads attempt to use th client.

My assumption is that connections are leased from the pool on a per-thread basis.  So how do I close a connection when the thread exits?

### Expected Behavior

NA

### Current Behavior

NA

### Reproduction Steps

NA

### AWS Java SDK version used

2.17.239

### JDK version used

NA

### Operating System and version

NA

**Comment by bartakj** [comment]
We're definitely running out of connections, but it appears to be because when a thread is terminated the connection associated with that thread isn't released.  So after enough threads get terminated and replaced we run out of connections.  It appears from our testing so far that once this starts happening it can't recover (although it's possible that if we waited longer and stopped terminating threads it would eventually recover).

Is there a way to release a connection?  Do the connections ever timeout if they aren't used?

**Comment by yasminetalby** [comment]
Hello @bartakj ,

> Is there a way to release a connection? 

_The connection should be automatically released if you close the thread._ 

> Do the connections ever timeout if they aren't used?

_You can use `connectionMaxIdleTime` to configure the maximum amount of time that a connection should be allowed to remain open while idle. By default this value is set to DEFAULT_CONNECTION_MAX_IDLE_TIMEOUT = Duration.ofSeconds(60);_ 

Could you please provide a code sample of your use case, the HTTP Client used and the log associated with the behavior? This will allow me to have a better understanding of your use case and provide appropriate guidance here. 
The SDK Client metrics would also be useful to have a better understanding of what is causing ` Timeout waiting for connection from pool` and how to tune the HTTP Client.

Best,

Yasmine
