### ISSUE TITLE
Cannot create tag without value for DeleteTagsRequest

### ISSUE THREAD

**Issue by MartinEmrich** [aws/aws-sdk-java-v2#3654]
### Describe the bug

I want to delete a tag from an EC2 instance. The documentation states *If you specify a tag key without a tag value, we delete any tag with this key regardless of its value.*

So I tried
````
		Tag removeTag = Tag.builder().key(keyToRemove).build(); // without .value(xxx)
		DeleteTagsRequest deleteTagsRequest = DeleteTagsRequest.builder().resources(instanceId).tags(removeTag)
				.build();

		AWSEC2RequestRetrier.doWithRetries(() -> {
			conn.getEC2Client().deleteTags(deleteTagsRequest);
		});
````

### Expected Behavior

I would have expected that the call is processed, and the given tag is removed from the instance.

### Current Behavior

But the result is an error:
````
software.amazon.awssdk.services.ec2.model.Ec2Exception: Tag specification resource type must have a value (Service: Ec2, Status Code: 400, Request ID: xxx)
````
Looks like this is processed server-side.

### Reproduction Steps

see code example above.

### Possible Solution

Accept a builder call chain without `.value()` as valid for the DeleteTagsRequest. Or have it take a list of key strings instead of *Tag* objects for the tags to remove completely.

Using an empty string probably does not work, as the empty string would be a valid value for a tag itself.

### AWS Java SDK version used

2.17

### JDK version used

Amazon Corretto 17

### Operating System and version

Amazon Linux 2

**Comment by MartinEmrich** [comment]
Just tried with `.value(null)` as well, same result.

**Comment by yasminetalby** [comment]
Hello @MartinEmrich ,

Thank you very much for your submission. 

I have conducted some testing using the latest version of the SDK (v2.19.1) and I am not able to reproduce the behavior you are describing.
The SDK behave as described in the [documentation](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/ec2/model/DeleteTagsRequest.Builder.html#tags(software.amazon.awssdk.services.ec2.model.Tag...)) that is,  _If you specify a tag key without a tag value, we delete any tag with this key regardless of its value_ .

Note, I have also tested this with v2.17.1 to best match your use case and the behavior is also the correct one.
```
   String instanceId = "instance-id";
       Tag tag = Tag.builder().key("KeyName").build();
       DeleteTagsRequest deleteTagsRequest = DeleteTagsRequest.builder().resources(instanceId).tags(tag)
               .build();
       Ec2Client client = Ec2Client.builder().region(Region.US_WEST_1).build();
       client.deleteTags(deleteTagsRequest);
```

The exception `software.amazon.awssdk.services.ec2.model.Ec2Exception: Tag specification resource type must have a value (Service: Ec2, Status Code: 400, Request ID: xxx)` indicates that the resource type must have a value and might be caused by a misuse of [TagSpecification](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TagSpecification.html).


Best,

Yasmine

**Comment by MartinEmrich** [comment]
Thanks. After filling it up with debug log messages and trying again today, it worked. So either I hit a heisenbug or a transitory issue yesterday. This (which IMHO does not differ from the more terse, first version):

````
		String instanceId = getID(conn);

		Tag removeTag = Tag.builder().key(keyToRemove).build();
		DeleteTagsRequest deleteTagsRequest = DeleteTagsRequest.builder().resources(instanceId).tags(removeTag)
				.build();

		logger.debug("DeleteTagsRequest is {}", ReflectionToStringBuilder.toString(deleteTagsRequest));

		try {
			AWSEC2RequestRetrier.doWithRetries(() -> {
				conn.getEC2Client().deleteTags(deleteTagsRequest);
			});
		} catch (Throwable t) {
			logger.debug("Executing deleteTags resulted in {}", t.getMessage(), t);
		}
`````
worked flawlessly:
````
DeleteTagsRequest is software.amazon.awssdk.services.ec2.model.DeleteTagsRequest@783b1742[resources=[i-<myCorrectInstanceId>],tags=[Tag(Key=<myCorrectTag>)],requestOverrideConfig=<null>]
````
No exception, and the tag disappeared correctly.

Strange, but anyway thanks for your help! (I'll go to 2.19 soon, anyways)
