### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by Maheshwaran1298** [aws/aws-sdk-java-v2#4055]
### Describe the issue

I am also facing the same issue please tell me how to resolve this iisue "unable to execute http request pkix path building failed"

### Links

I am also facing the same issue please tell me how to resolve this iisue "unable to execute http request pkix path building failed"

**Comment by debora-ito** [comment]
@Maheshwaran1298 it's not clear how this is a documentation issue. Please give more information on the issue so we can help you better. 

If this is a bug report, please open a [New Bug Report](https://github.com/aws/aws-sdk-java-v2/issues/new/choose) and fill all the fields in the template.

If you're seeing certificate issues, you can do a search in this repository for previous reports of the error, like [this one](https://github.com/aws/aws-sdk-java-v2/issues/1443#issuecomment-536055043).

**Comment by Maheshwaran1298** [comment]
@debora-ito 
Below I attached two screenshot one is code and another one is error logs 
![20230602_202321](https://github.com/aws/aws-sdk-java-v2/assets/135136537/4fab98ef-fec6-47b0-b4e6-2a2bce9ad09c)
![20230602_202542](https://github.com/aws/aws-sdk-java-v2/assets/135136537/31e0cef5-4b57-4dac-b46d-be200e7fa2fb)

**Comment by debora-ito** [comment]
@Maheshwaran1298 I deleted your code snippet because it exposed your aws credentials - **please rotate your credentials as soon as possible** to avoid your resources being exploited.

As for the "PKIX path" error, please refer to [this comment](https://github.com/aws/aws-sdk-java-v2/issues/1443#issuecomment-536055043), the needed certificates are probably missing from your trust store. The trust store is a configuration done at the JDK level, outside the SDK. For more information on how to configure the trust store, please check the documentation of the JDK you are using.

**Comment by Maheshwaran1298** [comment]
@debora-ito 
Actually we don't aware of this certificate please tell me how to update and which certificate need to update and how many steps in process of update certificate

**Comment by Maheshwaran1298** [comment]
@debora-ito please tell how to resolve we are facing so long this issue

**Comment by debora-ito** [comment]
It's all explained in the blog post I referenced previously -
https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/

Please read the blog post and make sure the certificates listed in it are present in your trust store.
