### ISSUE TITLE
S3 HeadObject returns ReplicationStatus=COMPLETED while in API you have ReplicationStatus.COMPLETE

### ISSUE THREAD

**Issue by lukaszlenart** [aws/aws-sdk-java-v2#4152]
### Describe the bug

Setup a S3 bucket replication, request status of a file in the origin bucket, you will get the following response

```scala
HeadObjectResponse(..., Metadata={}, ReplicationStatus=COMPLETED)
```

the problem is when you use `ReplicationStatus` enum there is `COMPLETE` instead of `COMPLETED` and you are ending with `UNKNOWN_TO_SDK_VERSION` state.

### Expected Behavior

SDK should match the status returned by the endpoint

### Current Behavior

ReplicationStatus.COMPLETE != ReplicationStatus=COMPLETED

### Reproduction Steps

You must have a replication between S3 buckets defined, put a file in one bucket and check its status using 
```scala
HeadObjectRequest.builder().bucket(bucketNameStr).key(fileKeyStr).build()
val response = s3Client.headObject(request)
```

### AWS Java SDK version used

2.20.92

### JDK version used

17

### Operating System and version

macOS Ventura 13.4.1 (22F82)

**Comment by lukaszlenart** [comment]
[Here](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/resources/codegen-resources/service-2.json#L9421) is the bug, supposed to be `COMPLETED`

**Comment by debora-ito** [comment]
@lukaszlenart thank you for the PR but we won't be able to merge it.

Any change in the service model must be made upstream, so that all the SDKs (not only Java) can benefit from the fix. Each service is responsible for maintaining their model, so this must be fixed by the S3 team.

This was previously reported here: https://github.com/aws/aws-sdk/issues/242 - please track that link for updates.
