### ISSUE TITLE
UpdateItemEnhancedRequest does not allow specification of the ReturnItems member of the updateItem API call

### ISSUE THREAD

**Issue by rawlinsc** [aws/aws-sdk-java-v2#4247]
### Describe the feature

The UpdateItem API call defines the [ReturnItems](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ReturnValues) member of the Request structure that allows callers to specify NONE | ALL_OLD | UPDATED_OLD | ALL_NEW | UPDATED_NEW for the values returned by the updateItem API call.

### Use Case

I have a use case where I need to modify another table based on the changes between one column of a table when a row gets updated and would like to use the old values that were consistent prior to the update request, e.g. the ALL_OLD or UPDATED_OLD.

### Proposed Solution

Add a member to the UpdateItemEnhancedRequest.Builder named returnItems, that accepts values from the com.amazonaws.services.dynamodbv2.model.ReturnValue enum, and defaults to the current behaviour ALL_NEW,  and pass it to the request instead of the constant ALL_NEW.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2

### JDK version used

17

### Operating System and version

AL2012

**Comment by debora-ito** [comment]
I see. `ReturnValues` is supported in PutItemEnhancedRequest but not in UpdateItemEnhancedRequest. Feature request acknowledged.

Community note: please show your support by adding a 👍 to the original description above to help us prioritize this request.

**Comment by masakiasanuma** [comment]
Hi @debora-ito, is there an ETA for this feature to be added? I was experimenting with a workaround by using the regular `UpdateItemRequest` instead, but the amount of changes required to use the non-enhanced client for this specific feature did not seem feasible/worth it. 

I would greatly appreciate if we can somehow accelerate this feature so that my team can utilize it for one of our services. I understand that there are higher priority tasks to be worked on, so I was wondering if there would be a realistic completion time for this request.

Thanks!

**Comment by debora-ito** [comment]
This is now supported in SDK version [2.26.10](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#22610-2024-06-26).
