### ISSUE TITLE
AWS Inspector Reported Netty vulnerability

### ISSUE THREAD

**Issue by keenhon** [aws/aws-sdk-java-v2#4390]
### Describe the feature

https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268

Netty 4.1.94.Final has issue as reported by AWS Inspector

### Use Case

Our security team requires us to fix vulnerabilities

### Proposed Solution

Please upgrade Netty version.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.140

### JDK version used

11

### Operating System and version

Lambda Coretto 11

**Comment by debora-ito** [comment]
@keenhon we'll investigate if Java SDK v2 is impacted by [CWE-295](https://cwe.mitre.org/data/definitions/295.html). As it's described in the netty issues, looks like it's a matter of making the validation manually.

Upgrading the netty version is not an option right now, the "fix" will only be available in netty 5.x and won't be backported to 4.1.x. Netty 5.x is not GA yet.

**Comment by zoewangg** [comment]
Thanks for your message regarding the improper certificate validation issue within Netty HTTP client.

The AWS SDK for Java v2 is not impacted by [CWE-295 - Improper Certificate Validation](https://cwe.mitre.org/data/definitions/295.html) because [hostname verification is explicitly enabled in the SDK](https://github.com/aws/aws-sdk-java-v2/blob/d6b3809104a8e8429725561411f325b142341af6/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java#L328).
