### ISSUE TITLE
When '/' is included in the bucket path, the path is always changed to %2f and the yml file cannot be read.(spring config server using sdk v2)

### ISSUE THREAD

**Issue by dnxodl** [aws/aws-sdk-java-v2#4714]
### Describe the bug

When '/' is included in the bucket path, the path is always changed to %2f and the yml file cannot be read.

I set the following settings in the yml file in Spring Boot (3.0.6) and use it as a spring config server. When used like this, it worked normally in java sdk version 1, but in version 2, '/' is encoded as %2F, so properties are not received properly.

Please confirm this.
         
   profiles:
     active: local, awss3
   cloud:
     config:
       enabled: true
       server:
               awss3:
                 region: ap-northeast-2
                 bucket: test-bucket/configuration

### Expected Behavior

DEBUG 16976 --- [nio-8037-exec-1] o.a.http.impl.execchain.MainClientExec   : Executing request GET /test-bucket/configuration/ad-whale-external-local.properties HTTP/1.1

### Current Behavior

DEBUG 16976 --- [nio-8037-exec-1] o.a.http.impl.execchain.MainClientExec   : Executing request GET /test-bucket%2Fconfiguration/ad-whale-external-local.properties HTTP/1.1

### Reproduction Steps

No response

### AWS Java SDK version used

2.21.26

### JDK version used

17.0.7

### Operating System and version

Window 10

**Comment by debora-ito** [comment]
@dnxodl Yes, this is expected. The Java SDK will url encode the bucket name in the requests.

Bucket names can't have slashes '/' in S3 - see S3 bucket naming rules [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html). So instead of using `bucket: test-bucket/configuration`, you should use `test-bucket` as bucket name, and `configuration` as the object key prefix (e.g. object key should be `configuration/ad-whale-external-local.properties`).
