### ISSUE TITLE
http-auth and http-auth-spi 2.21.42 not available from Maven Central

### ISSUE THREAD

**Issue by veita** [aws/aws-sdk-java-v2#4773]
### Describe the bug

https://repo1.maven.org/maven2/software/amazon/awssdk/http-auth/
https://repo1.maven.org/maven2/software/amazon/awssdk/http-auth-spi/

Both directories do not show 2.21.42 subdirectories. This seems to be linked to failures in our Gradle builds (with `version: '2.21.+'`).

### Expected Behavior

Gradle builds should succeed with
```
group: 'software.amazon.awssdk', name: 'http-auth',     version: '2.21.+'
group: 'software.amazon.awssdk', name: 'http-auth-spi', version: '2.21.+'
```

### Current Behavior

Gradle builds failed. After playing around with explicit versions specified a build finally succeeded, probably due to local caching.

### Reproduction Steps

N.A.

### AWS Java SDK version used

2.21.42

### JDK version used

17.0.9

### Operating System and version

Linux Mint 21.2

**Comment by debora-ito** [comment]
@veita we can't tell why `2.21.42` and `2.21.43` are not showing in that maven repo list right now, but there were no errors on our side when publishing those two versions to maven central. Once the release is finished, the timeline for when the version will be available in maven central is out of our control, it can take several hours for the versions to show up in that list.

That said, versions `2.21.42` and `2.21.43` are showing in the [`central.sonatype.com`](https://central.sonatype.com/artifact/software.amazon.awssdk/http-auth/versions), and pinning those versions specifically (instead of using '2.21.+') is working fine on my local environment.

Can you pin a specific version, instead of using '2.21.+'?
If not, can you share the logs of the build failure and your build gradle file?

**Comment by debora-ito** [comment]
We've reached out to the Sonatype team, and looks like they're receiving similar reports across the board in the past few days - https://issues.sonatype.org/browse/OSSRH-97493

The index was restored, and the latest SDK versions are showing up now - https://repo1.maven.org/maven2/software/amazon/awssdk/http-auth/.

This issue will auto close soon. Let us know if you have follow-up questions.
