### ISSUE TITLE
Add explicit ForbiddenException to IoT HTTP API Response

### ISSUE THREAD

**Issue by anttang8** [aws/aws-sdk-java-v2#4870]
### Describe the feature

Currently, AWS SDK does not throw a Forbidden Exception when a 403 is returned from IoT HTTP calls, but rather, a generic AWSIotDataException is returned with the status code of 403. 

The behavior could be better to inform the customer exact exception like there is for the other non-success codes. For instance, in https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-iot/src/main/java/com/amazonaws/services/iotdata/AWSIotDataClient.java, there are a number of exceptions that can be thrown (for instance, ServiceUnavailableException) -- all of these derive from:

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/iotdata/model/AWSIotDataException.html

And none of them are ForbiddenException.

### Use Case

To have a more accurate and obvious exception thrown for forbidden cases.

### Proposed Solution

Throw a forbidden exception (maybe ForbiddenException), not a generic AWSIotDataException when HTTP paths return a 403.

> 

### Other Information

The breaking change detailed below is if the ForbiddenException isn't derived from AWSIotDataException -- might break devices which has specific logic around AWSIotDataException. If ForbiddenException is derived from AWSIotDataException, this shouldn't be an issue.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS Java SDK version used

Latest has this code

### JDK version used

N/A

### Operating System and version

N/A

**Comment by debora-ito** [comment]
@anttang8 

For the Java SDK to throw a specific exception type, that exception needs to be modeled and associated with the operation. 

If the SDK can't map the exception received to any of the modeled exception types, it will fall back to the base generic service exception.

The IotDataPlane service team will need to add the Forbidden Exception to their model, because it's not listed currently -
https://github.com/aws/aws-sdk-java-v2/blob/master/services/iotdataplane/src/main/resources/codegen-resources/service-2.json

I can reach out internally to the IotData team and ask to update their model. Which IotDataPlane APIs are returning ForbiddenException?

**Comment by debora-ito** [comment]
Closing this, as @anttang8 will work internally to make the update.
