### ISSUE TITLE
transactWriteItems can use ReturnValues to get written items on successful write

### ISSUE THREAD

**Issue by bengaudiosi-toast** [aws/aws-sdk-java-v2#5629]
### Describe the feature

Right now, if you have a successful transact write items request, you need to read that value back to get its new state.

Other write operations, like `PutItemEnhancedRequest` and `UpdateItemEnhancedRequest`, allow you specify `ReturnValues` as an option to get these values back as part of the response for no additional read capacity.

### Use Case

When we utilize `@DynamoDbVersionAttribute`, version numbers for optimistic locking are automatically updated as part of the client call. 

We can manually update these ourselves client side to have the updated version, or re-read the object from the DB, but I'd rather the updated object could be included as part of the response.

### Proposed Solution

The `ReturnValues` feature should also exist on the respective `TransactPutItemEnhancedRequest` and `TransactUpdateItemEnhancedRequest` requests, and any updated items should be included in the response if these values are set.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.27.24

### JDK version used

openjdk 17.0.9 2023-10-17 LTS

### Operating System and version

macOS Sonoma 14.5

**Comment by RanVaknin** [comment]
Hi @bengaudiosi-toast ,

Thanks for opening the issue. This feature you are asking for is not an SDK feature but rather an API feature request. The SDK is a client and there has to be server side support for this feature for it to exist in the SDK.

I have created an internal feature request with the DDB team on your behalf (internal PFR ID `a2vRU000000GfSDYA0`) however we do not have visibility to when / if this will get implemented. My suggestion is to keep an eye out for announcements from DDB / our release notes to see if this was added. 

Since this is not directly actionable by the SDK team, I'm going to go ahead and close this. 

Thanks again,
Ran~
