### ISSUE TITLE
':' is not supported when reading credentials file

### ISSUE THREAD

**Issue by ruiarodrigues** [aws/aws-sdk-java-v2#5641]
### Describe the bug

The same support that has been done for the AWS Go sdk should be done for the AWS java sdk v2.
https://github.com/aws/aws-sdk-go/issues/366

When creating a S3 client using the java sdk v2, the files in .aws folder are read. The credentials file can have the syntax and AWS CLI can work fine with it. But the sdk fails stating that it's expecting an "=". The [ProfileFileReader](https://github.com/aws/aws-sdk-java-v2/blob/795fd45fade78b8bbbc0ca8e8ccf39c20ebfc4cd/core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java#L244) only supports "=". 

```
[blat]
aws_access_key_id: something
aws_secret_access_key: something
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

S3 client can be created with config files using "=" and ":" for properties

### Current Behavior

The creation of the client fails when the credentials file uses ":" for properties

### Reproduction Steps

Create a credentials file as shown in the description.
Crean an S3 client using sdk v2.

### Possible Solution

Support ":" for properties

### AWS Java SDK version used

2.27.17

### JDK version used

11

### Operating System and version

MacOs

**Comment by aniruddha789** [comment]
Is this tested on Windows OS

**Comment by ruiarodrigues** [comment]
I think it doesn't really matter. It's the content of the file that is not supported.

**Comment by debora-ito** [comment]
This is not a bug. Even though colon ":" works in AWS CLI, the Java SDK v2 supports the format documented in the AWS SDKs [Reference Guide](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html). 

We are paying more attention to cross-SDK standards now than at the time the change was made in the Go SDK, and I can say this has a low chance to be implemented because the change is specially hard in some language SDKs in which their native INI parser doesn't support colon. 

The recommendation here is to use "=".
