### ISSUE TITLE
Maven coordinates

### ISSUE THREAD

**Issue by davidmoten** [aws/aws-sdk-java-v2#642]
I'm a bit curious about the selection of maven coordinates for this project.

Currently they are:

```xml
<dependency>
  <groupId>software.amazon.awssdk</groupId>
  <artifactId>aws-sdk-java</artifactId>
  <version>2.0.0-preview-11</version>
</dependency>
```
I'd like to suggest that the notion of v2 should be in the artifactId rather than in the version. The reason for this is that the semantic versioning convention demands that a breaking change to the api bring about a change in the major version of the project. The current versioning scheme will not make this possible and thus in theory we won't be able to make breaking changes to the api as soon as we are out of preview which is very constraining.

My suggestion is we define the artifact like this instead:

```xml
<dependency>
  <groupId>software.amazon.awssdk</groupId>
  <artifactId>aws-sdk-java-v2</artifactId>
  <version>1.0.0-preview-11</version>
</dependency>
```

**Comment by millems** [comment]
The thought process was that we don't intend to make breaking API changes any time in the next 3-5 years. If we do end up having to do so, we can add the `-v3` to the artifact ID at that time (in addition to changing the root package name of the entire SDK to ensure that v2 and v3 can run in parallel).

I'm not against your second proposal, but would still prefer it to be `<version>2.0.0-preview-11</version>`, so that we can more easily differentiate between 1.11 and 2.1 in casual conversation without having to say "V1's 1.11" or "V2's "1.1". I'll let other people weigh in, though. We've had similar conversations before and the sentiment from others has always been "just add `-v3` later when it happens".

**Comment by davidmoten** [comment]
No breaking api changes is pretty optimistic, you won't get that much testing and feedback till your out of preview surely. 

In other projects that have taken this approach they've come up with a variant on semver which allows for breaking changes on the minor version (MAJOR.MINOR.PATCH). Ugly for its lack of consistency with the rest of the world but you could use it if you adopt the convention now (and make it clear on the README).

**Comment by spfink** [comment]
We've got additional details on our versioning scheme in this issue:

https://github.com/aws/aws-sdk-java-v2/issues/888

Closing this issue as we can't make this change at this point and are happy with our current versioning scheme. Feel free to add comments / thoughts to the above thread.
