### ISSUE TITLE
Ambigious AttributeValue in Preview 11

### ISSUE THREAD

**Issue by RyanHoldren** [aws/aws-sdk-java-v2#643]
I am using this new SDK with DynamoDB. I have just upgraded from preview 10 to preview 11. In preview 10, `AttributeValue.m()` returned `null` when the attribute value was not actually a map and `AttributeValue.l()` likewise returned `null` when the value was not actually a list. In preview 11 however, `AttributeValue.m()` returns an empty map instead and likewise `AttributeValue.l()` returns an empty list. This is very problematic because there is no longer any way to tell the difference between an empty array and an empty map.

## Possible Solution
- Go back to returning `null`
- Add a `AttributeValueType getType()` to `AttributeValue`

## Context
I am serializing Java objects using Jackson, then converting the JSON into `Map<String, AttributeValue>` to store it in DynamoDB. Later, the `Map<String, AttributeValue>` are converted back to a JSON tree, which is deserialized using Jackson.

## Environment
* AWS Java SDK version used: Preview 11
* JDK version used: OpenJDK 1.8.0.111
* Operating System and version: Debian “jessie”

**Comment by dagnir** [comment]
Hi @RyanHoldren, thanks for bringing this to our attention. This was an intentional change that we made so that the default values of all list and map members were instances of `SdkAutoConstructList` and `SdkAutoConstructMap` respectively as we felt this will help simplify user code by removing the need to check for both empty or `null` container members; however it also seems like it presents some interesting difficulties as you've pointed out.

Can you provide an example of your workflow? Since we ensure that these default empty lists or maps are these special `SdkAutoConstructList` and `SdkAutoConstructMap` interfaces, you might be able to use `instanceof` checks in place of `null` checks.

**Comment by RyanHoldren** [comment]
Thank you for the suggestion, I will give it a shot.

**Comment by RyanHoldren** [comment]
Yes that worked. Thank you, @dagnir.
