### ISSUE TITLE
Consider using jackson-modules-java8 instead of build serialization

### ISSUE THREAD

**Issue by zeldigas** [aws/aws-sdk-java-v2#8]
One of the most controversial things in [blog post](https://aws.amazon.com/ru/blogs/developer/aws-sdk-for-java-2-0-developer-preview/) is a serialization that should be done by using builders
```java
String serialized = mapper.writeValueAsString(request.toBuilder());

ListTablesRequest deserialized = mapper.readValue(serialized, ListTablesRequest.serializableBuilderClass())
                                       .build()
```
As you already set java 8 as a baseline and use jackson as a serialization library, why not use https://github.com/FasterXML/jackson-modules-java8 that will give you correct immutable object creation with constructor without extra manual step?

**Comment by shorea** [comment]
We are certainly open to it if it would help the serialization use case. Are you specifically referring to the parameter names support?

One thing I really want to do is leverage our new [marshallers](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/model/transform/PutItemRequestMarshaller.java#L32) to emit to common data formats like JSON, ION, CBOR, etc. The really cool thing about doing that is that we would be using the same field names defined in the service model so it becomes possible to serialize a service model object in the Java SDK and deserialize it in say the Ruby SDK. It could also be way more performant then reflection based mappers since we are essentially generating the serializer (which is something we have to do anyways to make the wire request).

**Comment by zeldigas** [comment]
If your long term plan is to have multi format support, then probably approach you described is more preferred. 
My suggestion was exactly about parameters name support - that would let Jackson use constructor initialization and avoid using intermediate builder.

**Comment by millems** [comment]
Tracking in #82
