### ISSUE TITLE
Create a ApacheHttpClient from a org.apache.http.impl.client.HttpClient

### ISSUE THREAD

**Issue by codefromthecrypt** [aws/aws-sdk-java-v2#852]
Here controls the builder used to make the http client. https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java#L117

Apache Http Client is hard to instrument, it would be easier if one could supply the base builder used.

## Expected Behavior
I'd expect to be able to pass an instance of `org.apache.http.impl.client.HttpClientBuilder`

## Current Behavior
The base builder is hard-coded

## Possible Solution
Add DefaultBuilder.setHttpClientBuilder

**Comment by millems** [comment]
What options are you interested in configuring on the `HttpClientBuilder` that aren't currently exposed by the SDK?

If the SDK took an `HttpClientBuilder`, we have three options: (a) override your settings with our own, or (b) override our own with your settings, (c) ignore all other client builder settings.

The first one isn't safe, because it makes it backwards incompatible for us to add new settings. 

The second one is safer, but harder to implement (how do we know what's already been set?). 

The third is probably the safest, but might be the hardest to discover. We would probably be an entirely different HTTP client builder to communicate that the other settings don't matter, and I'm not sure whether there are any settings that we would *have* to override on the client builder to make a successful call.

**Comment by adriancole** [comment]
unfortunately the only way this would work is overriding the base builder as the only way to change what is broken requires subtyping https://github.com/openzipkin/brave/blob/master/instrumentation/httpclient/src/main/java/brave/httpclient/TracingHttpClientBuilder.java

**Comment by adriancole** [comment]
"only way this would work" meaning "only way this would improve things"

**Comment by adriancole** [comment]
I agree that this feature could be mentioned as a use-at-own risk. FWIW in our tracing projects we often put in a test in our test tree to ensure we don't unknowingly mess up something. Knowing is the important part. IOTW, you could have a feature test in your tree that uses brave interceptor. Doing this is extreme, but you'd get some knowledge.

Other ways could be to make an observable client abstraction, but then again you'd have a double-instrumentation problem possibility which can be a worse problem than the one we are discussing which is config setting liability

**Comment by millems** [comment]
As an unrelated comment, for higher-level traceability we provide an [ExecutionInterceptor](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.java) that lets you see when requests are delegated to the HTTP client. If you're not interested in lower level details like connect times, it could be useful.

**Comment by adriancole** [comment]
I'll take your unrelated comment and raise you one :) here is Brian's work
in progress for tracing the new SDK
https://github.com/openzipkin/zipkin-aws/pull/112

**Comment by devinsba** [comment]
Re my PR: It would be nice to have the ability to not have to track the individual HTTP requests individually in the intercepter and rely on our, really well tested, client specific instrumentation for that. Then the SDK tracing component could just focus on the API/SDK concerns. This is the pattern we used in the V1 tracing wrapper so it works but it's not ideal
