### ISSUE TITLE
Semantic versioning when adding new service models

### ISSUE THREAD

**Issue by uriahcarpenter** [aws/aws-sdk-java-v2#888]
## Expected Behavior

From the [Semantic versioning website](https://semver.org): 
>Given a version number MAJOR.MINOR.PATCH, increment the:
>MAJOR version when you make incompatible API changes,
>MINOR version when you add functionality in a backwards-compatible manner, and
>PATCH version when you make backwards-compatible bug fixes.

When new AWS service models are added to the project, following SemVer rules, the MINOR version of the project should be incremented.

## Current Behavior

Recent releases (`2.1.2`, `2.1.3`) contain many newly introduced APIs for products announced at re:event 2018. The PATCH version was incremented for these releases.

## Possible Solution

Obviously, there are no SemVer police and you have not declared to follow the SemVer rules.  But I would argue that more projects are starting to follow the semantics defined in the SemVer manifesto and developers are starting to *expect* project version numbers follow SemVer rules.

I'm filling this issue because this project is relatively early in its lifecycle; it would be good to see clear and consistent version increments going forward.

**Comment by millems** [comment]
I knew this day would come! I'll jump under the bus on this one. We had a lot (read: A LOT) of internal discussion (read: arguing) about following semver for V2. There's frequently a lot of passionate arguments on both sides of this, and in my opinion, there's no absolutely 'correct' answer. We're open to input and are open to switching to semver in the future for this project.

Our versioning scheme (using the same MAJOR/MINOR/PATCH terms as semver for clarity in communication):

* **MAJOR**: Huge risk changes. This MUST be incremented when a change will break customers at compile time. This SHOULD be incremented when a change will break customers at runtime. (This is SHOULD because [every changes breaks someone](https://xkcd.com/1172/) and we'd like to be able to rely on human judgement.)
* **MINOR**: Medium risk changes. This MUST be incremented when there is a non-zero risk to upgrading, but the requirements for MAJOR aren't met. An example change of this nature would be increasing the minimum Java version or major refactors.
* **PATCH**: Zero risk changes: New features and bug fixes that don't affect existing code paths in any major way.

Like I said, we had a lot of internal discussion about following semver. There are a few problems with following semver in our project that made us believe that *not* following strict semver was *better* for the customer. I'll summarize a few reasons we decided not to go with semver below. Every point is debatable. We're a collection of people too, and we argue about these things as much as any other developers.

**Semver doesn't have a good way to distinguish between API backwards-compatibility and every other kind of backwards-compatibility.** 

"That's the point" is a valid argument, but we believe our customers wanted a bit more nuance. Customers frequently want to know the risk associated with a change, and we want our versioning to communicate an answer to that question. We want MAJOR to mean "yes, you could break", MINOR to mean "no, your code shouldn't break, but check the patch notes, because there's something you should know" and PATCH to mean "no, you won't break".

Some examples that might cause a MINOR version number bump:
1. If we make a significant refactor of core functionality. We'll obviously test the crap out of it, but there is some risk that an upgrade might cause unintended behavior changes. Maybe you shouldn't do this ugrade between a big QA spike and when you launch your product. Under semver there's no way to tell that 2.500.0 and 2.501.0 is zero-risk, but 2.501.0 to 2.502.0 has non-zero risk.
2. If we require a newer Java version than we did previously. E.g. If we noticed that the VAST majority of our customers are using Java 11+, and there are a lot of great features in Java 11 that we want to start using (additively) in the APIs of the SDK. Sticking to Java 8 would be sacrificing the needs of the many for the benefit of the few. For example, we might want to start supporting Java 9 publishers in addition to the current RX Java publishers.

**Under semver, we'd never use the PATCH version.**

We do semver MINOR version releases every day, and bugfixes just go out with those daily releases. That means that for us and for customers, the PATCH version would be useless... it would just be zero.

**Maven resolves dependency conflicts in a way that doesn't work well with semantic versioning.**

Maven uses closest-in-graph resolution, instead of highest-required-version and failing when there's a mismatched MAJOR. Because of this, there's always going to be a human element in resolving core/client mismatches. 

Incrementing the version number for every service with every daily release, regardless of whether it was changed, makes it easier to fix these problems by hand. The workflow for this is "s3 version 2.Y.Z requires at least version 2.Y.Z of the core packages to function correctly: upgrade that dependency". If these versions are incremented independently, then the workflow becomes "run mvn dependency:tree, find which version of the core libraries that S3 depends on, and pick a version that is at least that number." This starts to become even more complex when transitive dependencies start to pull in older versions of the SDK and a customer starts to use multiple clients: oldservice = 2.1.0 and newservice = 2.1.0 would have very different core version requirements under semver.

**Comment by uriahcarpenter** [comment]
Thanks for the clarifications; it's always good to have clarity on these types of design decisions.

I think many developers have a sentimental attachment to the MAJOR version that makes them resistant to change this number (often in the scope of years). My argument against your requirements for MAJOR and MINOR bumps would be: _are you going to use *this* repo for your next major paradigm refactoring?_ Just because `v2` is in the name of the repo does your library versioning scheme require that your MAJOR version is also `2` for the entire lifetime of the project?

>  If we make a significant refactor of core functionality. We'll obviously test the crap out of it, but there is some risk that an upgrade might cause unintended behavior changes. 

Even if your changes *should not be* API breaking, personally, I think this is where incrementing the MAJOR version makes sense. Allowing _relatively_ common updating of the MAJOR version would give me, as a developer, a lot more visibility of how changes in the SDK might affect my project. Your requirements for MAJOR and MINOR updates seam, to me, so grand that you will almost never update them. (e.g. Corretto 8 is expected to get security updates till [2023](https://www.infoq.com/news/2018/11/amazon-corretto-java) so bumping the MINOR for requiring Java 11 seems very, very, far out in the future.)

My unsolicited advice on when to bump versions:
 - **MAJOR:** Bump when you update between major and minor versions of upstream libraries (e.g. Jackson `2.8.x` --> `2.9.x`) and when other changes _may affect the behavior_ of my application. (Maybe 3-4 times per year.)
- **MINOR:** Mostly service model updates and developer ergonomics. I completely agree that all services move lockstep with this number.
- **PATCH:** Not used often (if ever) in your case because of the typical pace of MINOR releases.

Again, it's your project and I completely respect your decisions. However, from your MAJOR and MINOR requirements, it seems that you've almost boxed yourself into every update being a PATCH bump. Putting MAJOR and MINOR version numbers into common use would provide much-needed context (as much as a series of numbers can provide!) to developers on the level of risk they are assuming when revving the SDK dependency. Speaking as a developer who's been burned by PATCH updates in the v1 SDK. :)

**Comment by millems** [comment]
#943 is a great talking point on this discussion.

SDK customers must rewrite their whole application to move from version 1 to 2. Bumping to 3 for #943 could cause confusion, because 1 to 2 is a huge change, and 2 to 3 would be very small. Changes like #943 are a good candidate for going from 2.1 to 2.2 under our versioning system. There's some risk in it, but after looking at user agent metrics on the GetObject API we confirmed the majority of customers won't be affected.

Using "version 1" and "version 2" to differentiate between the two separately-supported versions of the product. It gives us a good way to communicate migration paths and support policies. It also gives customers an easy way to communicate what version of the library they are using. 

Examples of communication that's made easier with the current versioning system, and very difficult with semver:
1. 1.x will continue to be supported with bug fixes, security fixes, new services, and new APIs. 
2. 1.x and 2.x can be used in parallel within the same JVM.
3. Are you referring to version 1.x or 2.x?

Creating a different way of marketing the two libraries would be challenging. Even if 1.x stops being supported in the future, when a 3.x is launched in the (hopefully distant) future that majorly breaks backwards compatibility with 2.x, we'd run into the same problem.

The versioning system that the SDK uses currently could be labeled MARKETING.MAJOR.MINOR, where MAJOR and MINOR are strongly influenced by semver's MAJOR and MINOR.

**Comment by uriahcarpenter** [comment]
A scheme of `MARKETING.MAJOR.MINOR` seems like a very reasonable choice given the support issues involved with the large user base of the API.

I would emphasize that you consider incrementing the MAJOR number (in your scheme) when updating common dependent libraries (e.g. Apache HTTP Client, Jackson, etc.). The APIs of these libraries are frequently used directly in applications and can have behavior or configuration changes between versions. Even if the behavior of the AWS API may not change with a dependency update, _my_ code may be affected due to the update. (Of course, this is the exact problem Java 9 modules are solving, but many of us are still living in a classpath world!)

There was an [interesting discussion](https://jakewharton.com/java-interoperability-policy-for-major-version-updates/) around package naming and maven coordinates a few years ago when Retrofit 2 and OkHttp 3 where released.

I appreciate the time you've devoted to this subject.

**Comment by millems** [comment]
Thanks for all your feedback. +1 on bumping the MAJOR in this scheme for *any* dependency upgrades. Updating dependencies should be considered risky, regardless of what library that is. 

From your link, including the MARKETING version in the group id is a good idea, which should be considered for the SDK 3.x, since it can't easily be changed now.

**Comment by uriahcarpenter** [comment]
There seems to be consensus on how to handle breaking changes and major dependency upgrades.
